Criando listagem e remoção de Payer
JezVini/quickCharge pull request #21
Opened 2023-05-29 12:03 UTC by Jezreel-Moraes-Asaas

### Impacto

 - Adicionado a possibilidade de listar payers relacionados a um customer
 - Adicionado a possibilidade de desativar um payer
 - Modificado configuração de verificação de alteração de uma instância

### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento

> Listagem de payers :
 ![image](https://github.com/JezVini/quickCharge/assets/130087441/7fcf9f5d-e9a9-4b9f-b827-435b229c4c7f)

2023-05-29 13:35 UTC, welingtonloh requested changes

2023-05-29 13:35 UTC, welingtonloh commented on grails-app/conf/application.yml
> +    hibernateDirtyChecking: true
Pode manter nesse dessa forma, mas nos proximos quebrem os PRs por responsabilidade, daria para ser 3 Prs diferentes, resolvendo problemas diferentes:
1. Apenas dirtyCheck
2. Apenas removendo HTML dos gsps padroes do grails
3. A feature de fato (listagem de pagadores)

2023-05-29 13:35 UTC, welingtonloh commented on grails-app/views/payer/index.gsp
> +    <title>Todos Pagadores</title>
Dá uma olhada no PR que o @willevini fechou sobre listagem, tinhamos chegado num padrão de como deveria ser.

2023-05-29 13:35 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +        Payer validation = new Payer()
```suggestion
        Payer validatedPayer = new Payer()
```

2023-05-29 13:35 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +            throw new ValidationException("Erro ao desativar pagador", validation.errors)
```suggestion
            throw new ValidationException("Erro ao remover pagador", validation.errors)
```
O termo remover é mais adequado

2023-05-29 13:35 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +        return payer.save(failOnError: true, flush: true)
```suggestion
        return payer.save(failOnError: true)
```
Dá uma lida sobre para que serve failOnError e flush
Mas por hora, te asseguro que devemos usar o failOnError

2023-05-29 13:35 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            flash.message = "Pagador desativado com sucesso"
Padronizar mensagens e logs com o termo remover

2023-05-29 13:35 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +                return [invalidCustomer: true]
```suggestion
                return
```
Pode tentar usar dessa forma e validar no GSP se chegou uma lista de pagadores apenas

2023-05-29 13:35 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            return [customerId: customerId, payers: Payer.query(customerId: customerId, includeDeleted: false).list()]
```suggestion
            return [payerList: Payer.query(customerId: customerId, includeDeleted: false).list()]
```
Não precisa mandar esse customer pro GSP
Usa o padrão payerList, pois deixar claro que é um lista. Payers possui plural timido e pode passar batido o S

2023-05-29 15:21 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +            throw new ValidationException("Erro ao desativar pagador", validation.errors)
Podem seguir a regra:
Se for deleted = 1 >> remover
Se for deleted = 0 >> restaurar

Deixa esse termo "desativar" disponível para usar futuramente para outra coisa.

2023-05-29 16:26 UTC, Jezreel-Moraes-Asaas commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +            throw new ValidationException("Erro ao desativar pagador", validation.errors)
Feito

2023-05-29 16:27 UTC, Jezreel-Moraes-Asaas commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +                return [invalidCustomer: true]
Feito

2023-05-29 16:28 UTC, Jezreel-Moraes-Asaas commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            return [customerId: customerId, payers: Payer.query(customerId: customerId, includeDeleted: false).list()]
Feito

2023-05-29 16:33 UTC, Jezreel-Moraes-Asaas commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            return [customerId: customerId, payers: Payer.query(customerId: customerId, includeDeleted: false).list()]
Eu ainda não removi o customerId que estou passando pro GSP porque ele é usado na criação do link de edição de payer. Em breve vou fazer um PR para remover essa dependência de customerId por URL, ela não faz sentido.

2023-05-30 10:46 UTC, bmorais21 commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            return [payerList: Payer.query(customerId: customerId).list(), customerId: customerId]
ficou faltando colchetes, pois `query` espera receber um mapa 

```suggestion
            return [payerList: Payer.query([customerId: customerId]).list(), customerId: customerId]
```

2023-05-30 10:46 UTC, bmorais21 commented on grails-app/views/payer/index.gsp
> +    <g:if test="${payerList != null}">
Aqui podemos simplificar a verificação de existência da lista:

```suggestion
    <g:if test="${!payerList}">
```

2023-05-30 12:09 UTC, Jezreel-Moraes-Asaas commented on grails-app/views/payer/index.gsp
> +    <g:if test="${payerList != null}">
Eu fiz duas validações em cima de payerList, uma para verificar se o customer existe e outra para verificar se ele tinha algum payer.

![image](https://github.com/JezVini/quickCharge/assets/130087441/eb7d2565-604e-4808-8c51-fea531b9d733)

Quando o customer passado não existe, ele não retorna nada no map, então o valor de payerList é nulo, mas se o customer existir e não tiver nenhum payer, a lista existe, mas é vazia.

![image](https://github.com/JezVini/quickCharge/assets/130087441/a7aa733f-39ca-4d94-b5b0-9d3a8e4a10ad)

A validação:  " !payerList " retorna true pra quando payerList é nulo ou vazio, por isso tive que ser explicito na validação de nulo.

O resultado:

Customer existe e não tem payers:
![image](https://github.com/JezVini/quickCharge/assets/130087441/1f510636-d9fe-46c5-b5d9-bb9af87cccb3)

Customer não existe:
![image](https://github.com/JezVini/quickCharge/assets/130087441/84af2795-bf83-43d6-a927-222b95fe78fd)

2023-05-31 18:15 UTC, Jezreel-Moraes-Asaas commented on grails-app/views/payer/index.gsp
> +    <g:if test="${payerList != null}">
Feito

2023-06-01 13:59 UTC, KrlosEberhardt approved these changes

2023-06-01 14:00 UTC, merged