Criando envio de emails | EmailRequest
JezVini/quickCharge pull request #58
Opened 2023-06-17 01:42 UTC by Jezreel-Moraes-Asaas

### Impacto

- Criado domain EmailRequest para arquivar os emails a serem enviados no banco
- Criado service EmailRequestService para salvar e enviar emails
- Criado job SendEmailRequestJob para solicitar o envio dos emails a cada 5 segundos

### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento

2023-06-20 13:07 UTC, Yuri-Ferrari requested changes

2023-06-20 13:07 UTC, Yuri-Ferrari commented on grails-app/services/com/quickcharge/app/email/EmailRequestService.groovy
> +    void addEmail(Map email) {
Sempre usem modificadores de acesso: public, private, etc

2023-06-20 13:07 UTC, Yuri-Ferrari commented on grails-app/services/com/quickcharge/app/email/EmailRequestService.groovy
> +    void sendPendingEmails(def mailService) {
Por que receber service via parâmetro e não incluir diretamente nesse service a dependência?

2023-06-20 13:07 UTC, Yuri-Ferrari commented on grails-app/services/com/quickcharge/app/email/EmailRequestService.groovy
> +            EmailRequest emailRequest = emailRequestList.pop() as EmailRequest
Por quais motivos foi usado while ao invés de for que era o utilizado por vocês até então?

2023-06-20 13:07 UTC, Yuri-Ferrari commented on grails-app/services/com/quickcharge/app/email/EmailRequestService.groovy
> +            emailRequest.save(failOnError: true)
Criar um tratamento para caso houver um erro no envio de emails

2023-06-20 15:00 UTC, Jezreel-Moraes-Asaas commented on grails-app/services/com/quickcharge/app/email/EmailRequestService.groovy
> +    void sendPendingEmails(def mailService) {
Por algum motivo, mailService não é instanciado em EmailRequestService, assim como o caso do PageRenderer.
Ainda estou procurando soluções mas, até o momento, o que tem funcionado é pegar na força bruta, por exemplo:

`Holders.applicationContex.getBean("groovyPageRenderer").render(view: viewPath, model: args)`

Mas não parece uma boa solução também..

2023-06-21 14:21 UTC, Jezreel-Moraes-Asaas commented on grails-app/services/com/quickcharge/app/email/EmailRequestService.groovy
> +    void addEmail(Map email) {
Feito

2023-06-21 14:22 UTC, Jezreel-Moraes-Asaas commented on grails-app/services/com/quickcharge/app/email/EmailRequestService.groovy
> +    void sendPendingEmails(def mailService) {
Foi adicionada a dependência de mailService diretamente em EmailRequestService

2023-06-22 20:09 UTC, Yuri-Ferrari approved these changes

2023-06-22 20:24 UTC, merged