Implementação do Comprovante de Pagamento
JezVini/quickCharge pull request #59
Opened 2023-06-19 13:01 UTC by willevini

### Impacto
Implementação do Comprovante de Pagamento, sendo um novo domínio da aplicação.
- Possui um id long e um UUID, que é utilizado para acessar a o endpoint publicamente.
- O mesmo UUID também é utilizado num campo do Payment, para otimizar o botão de Comprovante de Pagamento na tela index de payment.

### Release Note (Descrição que irá no forno)

### PR Predecessora
#55 

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento

2023-06-20 13:52 UTC, Yuri-Ferrari requested changes

2023-06-20 13:52 UTC, Yuri-Ferrari commented on grails-app/controllers/com/quickcharge/app/payment/PaymentReceiptController.groovy
> +            log.info("PaymentReceiptController.show >> Erro ao consultar comprovante com parâmetros: [${params}] [Mensagem de erro]: ${exception.message}")
Se é um erro não deve ser logado como `info`

2023-06-20 13:52 UTC, Yuri-Ferrari commented on grails-app/controllers/com/quickcharge/app/payment/PaymentReceiptController.groovy
> +            return [receipt: receipt, billingType: BillingType]
Precisa enviar o enum no model?

2023-06-20 13:52 UTC, Yuri-Ferrari commented on grails-app/domain/com/quickcharge/app/payment/Payment.groovy
> +    String receiptUniqueId
```suggestion

    String receiptUniqueId
```
Deixa uma linha em branco entre cada um, fica melhor de ler

2023-06-20 13:52 UTC, Yuri-Ferrari commented on grails-app/services/com/quickcharge/app/payment/PaymentService.groovy
> +        payment.receiptUniqueId = paymentReceipt.uniqueId
Não acho necessário vincular duplamente o recibo com a cobrança, se o recibo já tem a referência da cobrança, a cobrança não precisa ter a referência do recibo

2023-06-21 18:50 UTC, willevini commented on grails-app/controllers/com/quickcharge/app/payment/PaymentReceiptController.groovy
> +            return [receipt: receipt, billingType: BillingType]
Removido envio do enum.

2023-06-21 18:51 UTC, willevini commented on grails-app/domain/com/quickcharge/app/payment/Payment.groovy
> +    String receiptUniqueId
Foi removido o receiptUniqueId de payment.

2023-06-21 18:51 UTC, willevini commented on grails-app/services/com/quickcharge/app/payment/PaymentService.groovy
> +        payment.receiptUniqueId = paymentReceipt.uniqueId
Ajustado. Agora o tratamento ocorre por um método no domínio de Payment que busca o uuid do PaymentReceipt.

2023-06-22 20:12 UTC, Yuri-Ferrari approved these changes

2023-06-22 20:25 UTC, merged