Implementando envio de notificações | EmailRequest
JezVini/quickCharge pull request #64
Opened 2023-06-22 17:32 UTC by Jezreel-Moraes-Asaas

### Impacto

 - Criado classe que salva os emails no banco
 - Implementado envio de notificações pra cada ação de Payment

### Release Note (Descrição que irá no forno)

### PR Predecessora
#58 
### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento

Para cobranças removidas:
![image](https://github.com/JezVini/quickCharge/assets/130087441/355d5fd0-2353-4194-abf7-8bc19b6dfe55)

Para demais cobranças:
![image](https://github.com/JezVini/quickCharge/assets/130087441/29ae120f-e723-485e-bd0a-401507c865d8)

2023-06-22 20:27 UTC, Yuri-Ferrari requested changes

2023-06-22 20:27 UTC, Yuri-Ferrari commented on grails-app/controllers/com/quickcharge/app/payment/PaymentController.groovy
> +            createEmail(payment, PaymentEmailAction.CREATED)
Regra de negócio deve ficar no service, coloca o envio de email dentro do save, mesma coisa pra outros pontos desse PR

2023-06-22 20:27 UTC, Yuri-Ferrari commented on grails-app/services/com/quickcharge/app/email/BuildEmailContentService.groovy
> +
```suggestion
```

2023-06-22 21:05 UTC, Jezreel-Moraes-Asaas commented on grails-app/controllers/com/quickcharge/app/payment/PaymentController.groovy
> +            createEmail(payment, PaymentEmailAction.CREATED)
Feito

2023-06-23 12:55 UTC, Yuri-Ferrari approved these changes

2023-06-23 13:05 UTC, merged