Estilizando o comprovante de pagamento
JezVini/quickCharge pull request #69
Opened 2023-06-26 14:16 UTC by willevini

### Impacto
Estilização do comprovante de pagamento.

### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento

![image](https://github.com/JezVini/quickCharge/assets/130087613/237dcccd-2dc7-4003-a88a-35043998a6c8)

2023-06-27 12:59 UTC, Yuri-Ferrari requested changes

2023-06-27 12:59 UTC, Yuri-Ferrari commented on grails-app/assets/stylesheets/paymentReceipt/paymentReceipt.css
> +header {
Sempre que possível crie classes e customize as classses, como foi feito acima com o 'mainContainer' pois além de ficar mais fácil a leitura e identificação do que está sendo estilizado, isso diminui a chance de dar problema e mais um elemento desse for criado no template e ser customizado erroneamente.

2023-06-27 18:20 UTC, willevini commented on grails-app/assets/stylesheets/paymentReceipt/paymentReceipt.css
> +header {
Ajustado os seletores para puxarem pelas classes.

2023-06-28 19:27 UTC, Yuri-Ferrari requested changes

2023-06-28 19:27 UTC, Yuri-Ferrari commented on grails-app/assets/stylesheets/paymentReceipt/paymentReceipt.css
> +
```suggestion
```

2023-06-28 19:27 UTC, Yuri-Ferrari commented on grails-app/assets/stylesheets/paymentReceipt/paymentReceipt.css
> +.headerContent h1 {
Crie uma classe pro h1 e pra outros elementos

2023-06-28 19:27 UTC, Yuri-Ferrari commented on grails-app/views/paymentReceipt/show.gsp
> +                                R$ ${String.format("%.2f", receipt.payment.value)} reais
Usar taglib, em outros pontos do PR também

2023-06-29 13:03 UTC, Yuri-Ferrari approved these changes

2023-06-29 13:14 UTC, merged