Criando baseentity
JezVini/quickCharge pull request #7
Opened 2023-05-17 19:07 UTC by willevini

### Impacto
Adição do BaseEntity, que irá estender todas as classes de domínio, definindo alguns atributos padrões e removendo o campo field da criação das tabelas.
### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento

2023-05-17 19:59 UTC, welingtonloh requested changes

2023-05-17 19:59 UTC, welingtonloh commented on src/main/groovy/utils/entity/BaseEntity.groovy
> +    long id
Não precisa do id, cria automático já

2023-05-17 19:59 UTC, welingtonloh commented on src/main/groovy/utils/entity/BaseEntity.groovy
> +    LocalDateTime createdAt
Usa Date dateCreated
Date lastUpdated

2023-05-17 19:59 UTC, welingtonloh commented on src/main/groovy/utils/entity/BaseEntity.groovy
> +    boolean deleted
```suggestion
    Boolean deleted
```
Sempre utilizamos as classes Boolean, String, Long, Integer (são melhores)

ao invés de tipos primitivos boolean, long

2023-05-17 19:59 UTC, welingtonloh commented on src/main/groovy/utils/entity/BaseEntity.groovy
> +        version false
Pode explicar pq?

---

Sem o tablePerHierarchy aqui?

2023-05-17 20:42 UTC, willevini commented on src/main/groovy/utils/entity/BaseEntity.groovy
> +        version false
Nós pensamos que não iríamos utilizar o campo version nas tabelas, portanto decidimos remover. 
Teremos que utilizar futuramente?

2023-05-18 12:53 UTC, welingtonloh commented on src/main/groovy/utils/entity/BaseEntity.groovy
> +        version false
Precisamos manter ele, é utilizado pelo Hibernate para controle de concorrência

Imagina que podem ter duas transações diferentes acessando o mesmo objeto (por exemplo duas jobs diferentes)

2023-05-18 12:56 UTC, welingtonloh commented
@willevini precisa mergear esse com a branch main, e resolver os conflitos

2023-05-18 19:07 UTC, merged