Implementando paginação | Pagination
JezVini/quickCharge pull request #71
Opened 2023-06-26 16:25 UTC by Jezreel-Moraes-Asaas

### Impacto

Implementada paginação na listagem de clientes e cobranças

 - Criado templates
 - Criado PaginationTagLib
 - Modificada listagem de clientes e cobranças | Payer e Payment

### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento
Paginação:
![video](https://github.com/JezVini/quickCharge/assets/130087441/954ae8bc-c860-4e5a-940d-7b88d6270303)

Ações:
![acoes](https://github.com/JezVini/quickCharge/assets/130087441/84c6dbde-a6de-48ce-8255-9320f8c38831)

2023-06-27 14:10 UTC, Yuri-Ferrari requested changes

2023-06-27 14:10 UTC, Yuri-Ferrari commented on grails-app/views/shared/templates/pagination/_footer.gsp
> +    <div class="pagination-controllers" style="display: flex">
Sugiro utilizar a [paginação padrão do grails](https://docs.grails.org/3.1.1/ref/Tags/paginate.html) ao invés de criar uma própria.

2023-06-27 14:36 UTC, Jezreel-Moraes-Asaas commented on grails-app/views/shared/templates/pagination/_footer.gsp
> +                const link = "${createLink(action: 'index', params: parameterMap)}" + "&max=" + maxValue
Como eu posso fazer isso? esse max vem pelo valor que o JavaScript tá pegando do elemento select, mas não achei uma forma de pegar isso com o Groovy, por isso tive essa abordagem (que eu não gostei).

2023-06-27 14:39 UTC, Jezreel-Moraes-Asaas commented on src/main/groovy/utils/controller/BaseController.groovy
> +        return 10
Não sei se entendi. Eu fiz essa abordagem pois os valores offset e max não são passados em lugar nenhum por padrão, então eles podem não existir ainda. Por isso, caso eles não existam eu retorno um valor padrão.

2023-06-27 14:42 UTC, Jezreel-Moraes-Asaas commented on grails-app/taglib/com/quickcharge/app/paginate/PaginationTagLib.groovy
> +            actionMap.delete.tooltip = "Cobrança removida"
Essa mensagem explica por que o botão está desabilitado, não é interessante o usuário ter esse feedback?

2023-06-27 14:54 UTC, Jezreel-Moraes-Asaas commented on grails-app/views/shared/templates/pagination/_footer.gsp
> +    <div class="pagination-controllers" style="display: flex">
Eu cheguei a usar, mas ele joga uns links no html, e eu queria usar os atlas-button pra ficar mais bonito.

2023-06-27 14:55 UTC, Jezreel-Moraes-Asaas commented on grails-app/views/shared/templates/pagination/_footer.gsp
> +    <div class="pagination-controllers" style="display: flex">
> Sugiro utilizar a [paginação padrão do grails](https://docs.grails.org/3.1.1/ref/Tags/paginate.html) ao invés de criar uma própria.

Eu cheguei a usar, mas ele joga uns links no html, e as vezes, e eu queria usar os atlas-button pra ficar mais bonito.

2023-06-27 14:56 UTC, Jezreel-Moraes-Asaas commented on grails-app/views/shared/templates/pagination/_footer.gsp
> +                const link = "${createLink(action: 'index', params: parameterMap)}" + "&max=" + maxValue
> Inclui o max no map de parâmetros

Como eu posso fazer isso? esse max vem pelo valor que o JavaScript tá pegando do elemento select, mas não achei uma forma de pegar isso com o Groovy, por isso tive essa abordagem (que eu não gostei).

2023-06-27 19:32 UTC, Jezreel-Moraes-Asaas commented on grails-app/assets/stylesheets/data-list/table-list.scss
> +table.list {
Adicionado classe nos elementos modificados

2023-06-27 19:33 UTC, Jezreel-Moraes-Asaas commented on grails-app/taglib/com/quickcharge/app/paginate/PaginationTagLib.groovy
> +                href    : ""
Removido alimentação de href

2023-06-27 19:40 UTC, Jezreel-Moraes-Asaas commented on grails-app/taglib/com/quickcharge/app/paginate/PaginationTagLib.groovy
> +        } else {
Feito

2023-06-28 12:35 UTC, Jezreel-Moraes-Asaas commented on grails-app/views/payment/templates/_list.gsp
> +                            <td class="value">R$ ${String.format("%,.2f", payment.value)}</td>
Feito

2023-06-28 14:53 UTC, Jezreel-Moraes-Asaas commented on src/main/groovy/utils/controller/BaseController.groovy
> +        return 10
Feito

2023-06-29 21:10 UTC, Yuri-Ferrari approved these changes

2023-06-30 13:45 UTC, merged