Modificando login e cadastro de usuário | Login e Register
JezVini/quickCharge pull request #76
Opened 2023-06-27 13:36 UTC by Jezreel-Moraes-Asaas

### Impacto

 - Modificado a tela de login
 - Criando layout para usuários deslogados

### Release Note (Descrição que irá no forno)

### PR Predecessora
#75 
### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento

Login:
![image](https://github.com/JezVini/quickCharge/assets/130087441/2ca7562a-b747-4b58-8cde-0e0c4253ea4d)

Cadastro de novo usuário
![image](https://github.com/JezVini/quickCharge/assets/130087441/3dd4d181-d5c6-4c54-b4f8-a17959158dc7)

2023-06-27 16:46 UTC, Jezreel-Moraes-Asaas commented on grails-app/assets/stylesheets/external.scss
> +body {
Feito

2023-06-28 18:12 UTC, Yuri-Ferrari requested changes

2023-06-28 18:12 UTC, Yuri-Ferrari commented on grails-app/assets/stylesheets/external.scss
> +.body {
Classe já ajuda muito a ter uma especificidade e prevenir erros, mas pra prevenir ainda mais, usem nomes mais específicos, nesse caso: 'external-container' e ai o header->'external-header'
Dessa forma se ocorrer algum bug e alguem incluir estilização com outra classe 'body', aí não vai gerar problemas

2023-06-29 12:22 UTC, Jezreel-Moraes-Asaas commented on grails-app/assets/stylesheets/external.scss
> +.body {
Feita a alteração dos nomes das classes.

2023-06-29 13:07 UTC, Yuri-Ferrari approved these changes

2023-06-29 13:07 UTC, Yuri-Ferrari commented on grails-app/assets/stylesheets/register.scss
> +.register-container {
Definem e usem um padrão de Case para classes, kebab-case ou camelCase

2023-06-29 13:32 UTC, merged