Criando Controller, Service e Domain de Payer
JezVini/quickCharge pull request #8
Opened 2023-05-18 18:51 UTC by Jezreel-Moraes-Asaas

### Impacto

Criado a classe Payer
Criado a classe PayerController com action para adicionar um novo Payer
Criado views create e show para criação e confirmação de criação de um Payer

### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento

2023-05-18 19:18 UTC, welingtonloh requested changes

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +        println(params)
println no PR? por favor remover

println é código de teste e não deve constar em nossos PRs

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +        if (params.payer) {
Tem certeza? a nossa index não deveria apontar para a listagem de pagadores?

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            println("Service erros encontrados")
Se der erro, utiliza flash.message para avisar o usuário
Se der sucesso, avise tbm

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/domain/com/quickcharge/app/payer/Payer.groovy
> +class Payer extends BasePerson{
Payer vazia?

Com quem ela se relaciona? tem uma entidade que deveriamos ter criado antes dela

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/domain/com/quickcharge/app/payer/Payer.groovy
> +class Payer extends BasePerson{
```suggestion
class Payer extends BasePerson {
```
Espaçamento

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +        payer.save()
```suggestion
        payer.save(failOnError: true)
```

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +        println("Controller Save chamado")
Inserir try catch para capturarmos exceptions

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +        Payer payer = validate(params)
Um bom exemplo de como deve ser um save e um validate

![image](https://github.com/JezVini/quickCharge/assets/13861122/9c665165-28bf-4f16-8e5c-21218e45ca3d)

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +
Remover linhas em branco

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/views/payer/create.gsp
> +    <title>Document</title>
Sem titulo?

2023-05-18 19:18 UTC, welingtonloh commented on grails-app/views/payer/show.gsp
> +    <meta name="layout" content="main" >
Se ele ainda não faz o que se propõe, não deve estar no PR

Há duas opções:
1. remover ele, ou
2. Implementar devidamente o que precisa o show

2023-05-18 19:23 UTC, Jezreel-Moraes-Asaas commented on grails-app/domain/com/quickcharge/app/payer/Payer.groovy
> +class Payer extends BasePerson{
Estou aguardando o PR do Customer para criar a dependência entre as classes, e então eu modificaria isso em outro PR...

2023-05-18 19:23 UTC, Jezreel-Moraes-Asaas commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            println("Service erros encontrados")
Show, vou ver isso

2023-05-22 14:12 UTC, Jezreel-Moraes-Asaas commented
> Na daily de hoje alinhamos vários pequenos ajustes que vamos precisar fazer para deixar essas classes numa estrutura padrão

👍

2023-05-22 17:07 UTC, welingtonloh commented on grails-app/domain/com/quickcharge/app/payer/Payer.groovy
> +
Pode remover essa linha em branco

2023-05-22 17:07 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/customer/CustomerService.groovy
> +        if (!params.email) {
Adiciona uma linha em branco entre um if e outro

2023-05-22 17:07 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/customer/CustomerService.groovy
> +        Customer customer = new Customer()
```suggestion
        Customer validatedCustomer = new Customer()
```
Assim deixamos claro que é um objeto de apenas validação

2023-05-22 17:27 UTC, Jezreel-Moraes-Asaas commented on grails-app/controllers/com/quickcharge/app/customer/CustomerController.groovy
> +            //flash.type = MessageType.SUCESS
@welingtonloh Opa boa tarde, então esse código que você comentou é do PR do @willevini  sobre o Customer, eu fiz o merge do PR dele como comentei hoje de manhã, mas eu esqueci (não sabia que precisava) de mudar a base do PR de main para o PR dele...

2023-05-23 17:07 UTC, willevini commented on grails-app/services/com/quickcharge/app/customer/CustomerService.groovy
> +        }
Teste realizado, funcional

2023-05-23 20:04 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            flash.message = "Ocorreu um erro ao criar pagador, contate o desenvolvimento"
Adiciona:
log.info("PayerController.save >> Erro ao salvar pagador ${params.id}")

2023-05-23 20:04 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +
Remover linha sobrando

2023-05-23 20:04 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +    public Payer validatePayer(Map params) {
```suggestion
    public Payer validateSave(Map params) {
```
Orienta a operação que está fazendo

2023-05-23 20:04 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +        if (payer.hasErrors()) {
O certo é essa validação estar depois da linha 11

2023-05-23 20:04 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +        payer.save(failOnError: true)
```suggestion
        return payer.save(failOnError: true)
```
Funciona e é mais direto

2023-05-23 20:04 UTC, welingtonloh commented on grails-app/views/payer/create.gsp
> +        <input type="text"  name="name" id="name" value="${name}" placeholder="Digite seu nome">
Aqui como é create, todos os values deveriam estar vazios

2023-05-23 20:04 UTC, welingtonloh commented on grails-app/views/payer/create.gsp
> +
Remover linha em branco e deixar bem indentado

2023-05-23 20:16 UTC, Jezreel-Moraes-Asaas commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +        return params
A gente colocou o return dos params para que, caso o usuário insira dados inválidos e tenha que refazer a solicitação de criação, os campos sejam preenchidos pelo valores que ele enviou, diminuindo o re trabalho do usuário.

2023-05-23 20:26 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +        return params
Discutam: https://github.com/JezVini/quickCharge/pull/9#discussion_r1202960289

2023-05-23 21:22 UTC, Jezreel-Moraes-Asaas commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            flash.message = "Ocorreu um erro ao criar pagador, contate o desenvolvimento"
Faz sentido logar o id de um pagador que não foi registrado?
E params.id não vai existir aqui ainda, pois o id do objeto é instanciado no banco.
Sera que não seria interessante logar os valores de params?

2023-05-23 22:01 UTC, welingtonloh commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +            flash.message = "Ocorreu um erro ao criar pagador, contate o desenvolvimento"
Sim, o params inteiro é mais efetivo

2023-05-24 12:41 UTC, Jezreel-Moraes-Asaas commented on grails-app/controllers/com/quickcharge/app/payer/PayerController.groovy
> +        return params
Removido o retorno de params para create

2023-05-24 12:44 UTC, Jezreel-Moraes-Asaas commented on grails-app/views/payer/create.gsp
> +        <input type="text"  name="name" id="name" value="${name}" placeholder="Digite seu nome">
Foram removidos os campos value

2023-05-24 13:21 UTC, welingtonloh approved these changes

2023-05-24 13:21 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +        }
Isso faz parte do validateSave tbm

2023-05-24 13:49 UTC, Jezreel-Moraes-Asaas commented on grails-app/services/com/quickcharge/app/payer/PayerService.groovy
> +        }
Verdade, vou alterar

2023-05-24 15:11 UTC, welingtonloh approved these changes

2023-05-24 17:23 UTC, welingtonloh commented
Favor verificar e resolver os conflitos

2023-05-24 21:38 UTC, welingtonloh approved these changes

2023-05-24 21:38 UTC, merged