Criando dashboard | Dashboarf
JezVini/quickCharge pull request #84
Opened 2023-06-30 18:50 UTC by Jezreel-Moraes-Asaas

### Impacto

### Release Note (Descrição que irá no forno)

### PR Predecessora

### Plano de deploy
- Antes do deploy:
- Depois do deploy:

### Link da tarefa no JIRA

### Link dos mockups

### Prints do desenvolvimento

2023-07-03 17:48 UTC, Yuri-Ferrari requested changes

2023-07-03 17:48 UTC, Yuri-Ferrari commented on grails-app/controllers/com/quickcharge/app/menu/DashboardController.groovy
> +            customer: getCurrentCustomer(),
Cria uma variável pra armazenar o valor do customer e depois utiliza ela pra passar em todos os lugares, isso economiza processamento

2023-07-03 17:48 UTC, Yuri-Ferrari commented on grails-app/assets/stylesheets/dashboard.scss
> +        th, td {
Criar classes

2023-07-03 17:48 UTC, Yuri-Ferrari commented on grails-app/services/com/quickcharge/app/payment/PaymentService.groovy
> +        }
É possível fazer um somatório direto na query usando o `sum`, [documentação](https://docs.grails.org/3.1.1/ref/Domain%20Classes/createCriteria.html)

2023-07-03 17:48 UTC, Yuri-Ferrari commented on grails-app/services/com/quickcharge/app/payment/PaymentService.groovy
> +            overdue: overduePaymentList.size(),
E usando o link acima aqui pode ser usado o `count`

2023-07-04 13:13 UTC, welingtonloh commented on grails-app/services/com/quickcharge/app/payment/PaymentService.groovy
> +        Double receivedValue = 0, toReceiveValue = 0
Utilizem BigDecimal para valores monetários

2023-07-05 01:38 UTC, Jezreel-Moraes-Asaas commented on grails-app/services/com/quickcharge/app/payment/PaymentService.groovy
> +        Double receivedValue = 0, toReceiveValue = 0
Para seguir o padrão atual do projeto, vou manter como Double para a soma dou valores, porém, essa pode ser uma modificação a ser feita no futuro no projeto.

2023-07-06 13:34 UTC, Yuri-Ferrari approved these changes

2023-07-06 13:43 UTC, merged